---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  tags: nginx_editing

- name: Copy index.html file
  ansible.builtin.copy:
    src: "./roles/nginx_editing/templates/index.html"
    dest: "/home/ansible-worker/www/stud-template/index.html"
    mode: '0644'
  tags: nginx_editing

- name: Set permissions for www-data group
  ansible.builtin.file:
    path: "/home/ansible-worker/www"
    owner: www-data
    group: ansible-worker
    mode: "0755"
    recurse: yes
  tags: nginx_editing

- name: Create Nginx configuration file
  ansible.builtin.template:
    src: "./roles/nginx_editing/templates/ansible.iphilka.ru.conf"
    dest: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
  notify: Restart Nginx
  tags: nginx_editing

- name: Enable Nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
    dest: "/etc/nginx/sites-enabled/ansible.iphilka.ru.conf"
    state: link
  tags: nginx_editing