---
- name: Clone repository
  ansible.builtin.git:
    repo: "https://github.com/iphilka/stud-template.git"
    dest: "/home/ansible-worker/www/stud-template"
    clone: yes
    update: no
  tags: git_clone